#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$DIR

echo ""
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "MAKE SURE YOU RAN THIS SCRIPT LIKE SO:"
echo "   \"\$ . add_to_ROS_PACKAGE_PATH"\"
echo ""
echo "IF YOU DID, ROS_PACKAGE_PATH SHOULD NOW BE:"
echo "   '$ROS_PACKAGE_PATH'"
echo ""
echo "CHECK BY RUNNING:"
echo "   \"\$ echo \$ROS_PACKAGE_PATH\""
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo ""