#!/bin/bash

export ROS_MASTER_URI="http://127.0.0.1:11311"
export ROS_IP=127.0.0.1

echo ""
echo ""
echo "MAKE SURE YOU RAN THIS SCRIPT LIKE SO:"
echo "   \"\$ . export_ROS_variables"\"
echo ""
echo "IF YOU DID, VARIABLES SHOULD NOW BE:"
echo "   ROS_MASTER_URI: '$ROS_MASTER_URI'"
echo "   ROS_IP: '$ROS_IP'"
echo ""
echo "CHECK BY RUNNING:"
echo "   \"\$ echo \$ROS_MASTER_URI\""
echo "AND"
echo "   \"\$ echo \$ROS_IP\""
echo ""
echo ""